jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deply to production
        run: ./deploy.sh
        env:
          API_KEY: ${{ secrets.PRODUCTION_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to production
      run: gh pr create --title "Automated PR" --body "This is an automated PR."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
